In [13]:
import pandas as pd 
import numpy as np 
import json
import re

In [14]:
question = pd.read_json(r'D:\python\financial statement prj\chatbot_financial_statement\data\deepseek-chat__v0_good.jsonl', lines=True)
question.head()

,ids,question,table,reasoning,sql,score,avg
0,242d4217-33d1-4c53-9922-17a6d0a4b8d2,Analyze the trend of the Return on Assets (ROA...,**Company Info**\n\n| stock_code | company_n...,### Step-by-step Analysis:\n\n1. **Identify th...,[-- ### quarterly_roa_trend_vcb_acb_2020_to_q3...,"[1, 1]",1
1,e9def022-01c5-4dce-a223-103ae6913cd9,Analyze the price-to-earnings (P/E) ratio for...,**Company Info**\n\n| stock_code | company_n...,To analyze the Price-to-Earnings (P/E) ratio f...,[-- ### P/E Ratio Analysis for Retail Companie...,"[1, 1]",1
2,c9ae9e06-2903-43c8-97ff-4398bdba15be,What were the interest coverage ratios for the...,**Company Info**\n\n| stock_code | company_n...,Here is the SQL query to retrieve the interest...,[-- ### interest_coverage_ratio_utilities_comp...,"[1, 1]",1
3,52f49b81-e91d-4ff3-82cf-a2a62ca14800,"For the banking companies (BID, EIB, OCB, CTG,...",**Company Info**\n\n| stock_code | company_n...,### Step-by-step Analysis:\n\n1. **Identify th...,[-- ### banking_companies_roe_roa_2020_to_q3_2...,"[1, 1]",1
4,04da7098-1b47-45cc-b2c5-d288de57e5c3,Analyze the Gross Profit Margin for each compa...,**category_code_ratio**\n\n| ratio_code | ra...,### Step-by-step Analysis:\n\n1. **Identify th...,[-- ### food_and_beverage_companies_gpm_vs_ind...,"[1, 1]",1

In [15]:
import re

def analyze_sql_complexity(sql_query):
    sql_query_cleaned = "\n".join([line.strip() for line in sql_query.splitlines() if line.strip() and not line.strip().startswith("--")])
    
    print("SQL Query after removing comments and excess whitespace:")
    print(sql_query_cleaned)
    print("\n--- Breakdown of SQL Query Counting ---")

    keywords = r"\b(SELECT|FROM|WHERE|GROUP BY|ORDER BY|JOIN|INNER JOIN|LEFT JOIN|RIGHT JOIN|UNION|EXCEPT|INTERSECT|HAVING|WITH|LIMIT|OFFSET|BETWEEN|IN|IS NULL|IS NOT NULL|DISTINCT|AND|OR|NOT|LIKE|IS|NULL|COUNT|SUM|AVG|MAX|MIN|EXISTS|ANY|ALL|COALESCE|IFNULL|RANK\(\)|DENSE_RANK\(\)|ROW_NUMBER\(\))\b"
    matches = re.findall(keywords, sql_query_cleaned)
    total_lines = len(matches)

    operations = {
        "JOIN": len(re.findall(r"\bJOIN\b", sql_query_cleaned)),
        "INNER JOIN": len(re.findall(r"\bINNER JOIN\b", sql_query_cleaned)),
        "LEFT JOIN": len(re.findall(r"\bLEFT JOIN\b", sql_query_cleaned)),
        "RIGHT JOIN": len(re.findall(r"\bRIGHT JOIN\b", sql_query_cleaned)),
        "CROSS JOIN": len(re.findall(r"\bCROSS JOIN\b", sql_query_cleaned)),
        "SELF JOIN": len(re.findall(r"\bSELF JOIN\b", sql_query_cleaned)),
        "LEFT OUTER JOIN": len(re.findall(r"\bLEFT OUTER JOIN\b", sql_query_cleaned)),
        "RIGHT OUTER JOIN": len(re.findall(r"\bRIGHT OUTER JOIN\b", sql_query_cleaned)),
        "OUTER JOIN": len(re.findall(r"\bOUTER JOIN\b", sql_query_cleaned)),
        "UNION": len(re.findall(r"\bUNION\b", sql_query_cleaned)),
        "UNION ALL": len(re.findall(r"\bUNION ALL\b", sql_query_cleaned)),
        "EXCEPT": len(re.findall(r"\bEXCEPT\b", sql_query_cleaned)),
        "EXCEPT ALL": len(re.findall(r"\bEXCEPT ALL\b", sql_query_cleaned)),
        "INTERSECT": len(re.findall(r"\bINTERSECT\b", sql_query_cleaned)),
        "INTERSECT ALL": len(re.findall(r"\bINTERSECT ALL\b", sql_query_cleaned)),
        "ORDER BY": len(re.findall(r"\bORDER BY\b", sql_query_cleaned)),
        "GROUP BY": len(re.findall(r"\bGROUP BY\b", sql_query_cleaned)),
        "WITH": len(re.findall(r"\bWITH\b", sql_query_cleaned)),  # CTEs
        "HAVING": len(re.findall(r"\bHAVING\b", sql_query_cleaned)),
        "DISTINCT": len(re.findall(r"\bDISTINCT\b", sql_query_cleaned)),
        "LIMIT": len(re.findall(r"\bLIMIT\b", sql_query_cleaned)),
        "OFFSET": len(re.findall(r"\bOFFSET\b", sql_query_cleaned)),
        "LIKE": len(re.findall(r"\bLIKE\b", sql_query_cleaned)),
        "IN": len(re.findall(r"\bIN\b", sql_query_cleaned)),
        "BETWEEN": len(re.findall(r"\bBETWEEN\b", sql_query_cleaned)),
        "IS NULL": len(re.findall(r"\bIS NULL\b", sql_query_cleaned)),
        "IS NOT NULL": len(re.findall(r"\bIS NOT NULL\b", sql_query_cleaned)),
        "NULL": len(re.findall(r"\bNULL\b", sql_query_cleaned)),
        "COUNT": len(re.findall(r"\bCOUNT\b", sql_query_cleaned)),
        "SUM": len(re.findall(r"\bSUM\b", sql_query_cleaned)),
        "AVG": len(re.findall(r"\bAVG\b", sql_query_cleaned)),
        "MAX": len(re.findall(r"\bMAX\b", sql_query_cleaned)),
        "MIN": len(re.findall(r"\bMIN\b", sql_query_cleaned)),
        "EXISTS": len(re.findall(r"\bEXISTS\b", sql_query_cleaned)),
        "ANY": len(re.findall(r"\bANY\b", sql_query_cleaned)),
        "ALL": len(re.findall(r"\bALL\b", sql_query_cleaned)),
        "COALESCE": len(re.findall(r"\bCOALESCE\b", sql_query_cleaned)),
        "IFNULL": len(re.findall(r"\bIFNULL\b", sql_query_cleaned)),
        "RANK()": len(re.findall(r"\bRANK\(\)", sql_query_cleaned)),
        "DENSE_RANK()": len(re.findall(r"\bDENSE_RANK\(\)", sql_query_cleaned)),
        "ROW_NUMBER()": len(re.findall(r"\bROW_NUMBER\(\)", sql_query_cleaned)),
    }

    for operation, count in operations.items():
        print(f"{operation}: {count}")

    print(f"\nTotal logical lines (including functions and keywords): {total_lines}")

    total_operations = sum(operations.values())
    complexity_score = total_operations / total_lines if total_lines > 0 else 0

    print("\n--- Operation Counts ---")
    for operation, count in operations.items():
        if count > 0:
            print(f"Found '{operation}': {count} occurrence(s)")

    print(f"\nTotal logical lines (functions/keywords in uppercase): {total_lines}")
    print(f"Total operations count: {total_operations}")
    print(f"Complexity score (operations per logical line): {complexity_score:.2f}")
    
    return {
        "total_lines": total_lines,
        "operations": operations,
        "total_operations": total_operations,
        "complexity_score": complexity_score
    }

In [16]:
def process_sql_queries(df):
    results = []

    for idx, row in df.iterrows():
        sql_queries = row.get('sql', [])
        
        if sql_queries:
            for sql_query in sql_queries:
                complexity_result = analyze_sql_complexity(sql_query)
                results.append({
                    "id": row.get("ids", None),
                    "question": row.get("question", None),
                    "sql_query": sql_query,
                    "complexity_result": complexity_result
                })
    
    return pd.DataFrame(results)

sql_complexity_df = process_sql_queries(question)

SQL Query after removing comments and excess whitespace:
SELECT
stock_code,
year,
quarter,
ratio_code,
data
FROM financial_ratio
WHERE ratio_code = 'ROA' -- ROA is the code for Return on Assets
AND stock_code IN ('VCB', 'ACB') -- Filter for Vietcombank and ACB
AND date_added BETWEEN '2020-01-01' AND '2024-09-30' -- Time range from 2020 to Q3 2024
AND quarter != 0 -- Exclude annual reports
ORDER BY stock_code, year, quarter;

--- Breakdown of SQL Query Counting ---
JOIN: 0
INNER JOIN: 0
LEFT JOIN: 0
RIGHT JOIN: 0
CROSS JOIN: 0
SELF JOIN: 0
LEFT OUTER JOIN: 0
RIGHT OUTER JOIN: 0
OUTER JOIN: 0
UNION: 0
UNION ALL: 0
EXCEPT: 0
EXCEPT ALL: 0
INTERSECT: 0
INTERSECT ALL: 0
ORDER BY: 1
GROUP BY: 0
WITH: 0
HAVING: 0
DISTINCT: 0
LIMIT: 0
OFFSET: 0
LIKE: 0
IN: 1
BETWEEN: 1
IS NULL: 0
IS NOT NULL: 0
NULL: 0
COUNT: 0
SUM: 0
AVG: 0
MAX: 0
MIN: 0
EXISTS: 0
ANY: 0
ALL: 0
COALESCE: 0
IFNULL: 0
RANK(): 0
DENSE_RANK(): 0
ROW_NUMBER(): 0

Total logical lines (including functions and keywords): 10

--- Operation Counts ---
Found 'ORDER BY': 1 occurrence(s)
Found 'IN': 1 occurrence(s)
Found 'BETWEEN': 1 occurrence(s)

Total logical lines (functions/keywords in uppercase): 10
Total operations count: 3
Complexity score (operations per logical line): 0.30
SQL Query after removing comments and excess whitespace:
WITH company_pe_ratios AS (
SELECT
fr.stock_code,
fr.year,
fr.quarter,
fr.data AS pe_ratio,
ci.industry
FROM financial_ratio fr
JOIN company_info ci ON fr.stock_code = ci.stock_code
WHERE fr.ratio_code = 'PE' -- Price-to-Earnings Ratio
AND fr.stock_code IN ('MWG', 'FRT', 'PSD')
AND fr.date_added BETWEEN '2020-01-01' AND '2024-09-30'
AND fr.quarter != 0 -- Exclude annual reports
),
industry_pe_ratios AS (
SELECT
ifr.year,
ifr.quarter,
ifr.data_mean AS industry_pe_ratio
FROM industry_financial_ratio ifr
WHERE ifr.ratio_code = 'PE' -- Price-to-Earnings Ratio
AND ifr.industry = 'Retail'
AND ifr.date_added BETWEEN '2020-01-01' AND '2024-09-30'
AND ifr.quarter != 0 -- Exclude annual reports
)
SELECT
cpr.stock_code,
cpr.quarter,
cpr.year,
cpr.pe_ratio,
ipr.industry_pe_ratio
FROM company_pe_ratios cpr
JOIN industry_pe_ratios ipr
ON cpr.year = ipr.year
AND cpr.quarter = ipr.quarter
ORDER BY cpr.year, cpr.quarter, cpr.stock_code
LIMIT 100;

--- Breakdown of SQL Query Counting ---
JOIN: 2
INNER JOIN: 0
LEFT JOIN: 0
RIGHT JOIN: 0
CROSS JOIN: 0
SELF JOIN: 0
LEFT OUTER JOIN: 0
RIGHT OUTER JOIN: 0
OUTER JOIN: 0
UNION: 0
UNION ALL: 0
EXCEPT: 0
EXCEPT ALL: 0
INTERSECT: 0
INTERSECT ALL: 0
ORDER BY: 1
GROUP BY: 0
WITH: 1
HAVING: 0
DISTINCT: 0
LIMIT: 1
OFFSET: 0
LIKE: 0
IN: 1
BETWEEN: 2
IS NULL: 0
IS NOT NULL: 0
NULL: 0
COUNT: 0
SUM: 0
AVG: 0
MAX: 0
MIN: 0
EXISTS: 0
ANY: 0
ALL: 0
COALESCE: 0
IFNULL: 0
RANK(): 0
DENSE_RANK(): 0
ROW_NUMBER(): 0

Total logical lines (including functions and keywords): 25

--- Operation Counts ---
Found 'JOIN': 2 occurrence(s)
Found 'ORDER BY': 1 occurrence(s)
Found 'WITH': 1 occurrence(s)
Found 'LIMIT': 1 occurrence(s)
Found 'IN': 1 occurrence(s)
Found 'BETWEEN': 2 occurrence(s)

Total logical lines (functions/keywords in uppercase): 25
Total operations count: 8
Complexity score (operations per logical line): 0.32
SQL Query after removing comments and excess whitespace:
WITH company_ratios AS (
SELECT
fr.stock_code,
fr.year,
fr.quarter,
fr.ratio_code,
fr.data AS company_ratio
FROM financial_ratio fr
JOIN company_info ci ON fr.stock_code = ci.stock_code
WHERE fr.ratio_code = 'ICR' -- Interest Coverage Ratio
AND ci.industry = 'Utilities (Electricity, Water & Gas)'
AND fr.stock_code IN ('REE', 'GAS', 'POW', 'PVG')
AND fr.date_added BETWEEN '2020-01-01' AND '2024-09-30'
AND fr.quarter != 0 -- Ensure we are only looking at quarterly data
),
industry_ratios AS (
SELECT
ifr.year,
ifr.quarter,
ifr.ratio_code,
ifr.data_mean AS industry_ratio
FROM industry_financial_ratio ifr
WHERE ifr.ratio_code = 'ICR' -- Interest Coverage Ratio
AND ifr.industry = 'Utilities (Electricity, Water & Gas)'
AND ifr.date_added BETWEEN '2020-01-01' AND '2024-09-30'
AND ifr.quarter != 0 -- Ensure we are only looking at quarterly data
)
SELECT
cr.stock_code,
cr.quarter,
cr.year,
cr.ratio_code,
cr.company_ratio AS data,
ir.industry_ratio
FROM company_ratios cr
JOIN industry_ratios ir ON cr.year = ir.year AND cr.quarter = ir.quarter
ORDER BY cr.stock_code, cr.year, cr.quarter
LIMIT 100;

--- Breakdown of SQL Query Counting ---
JOIN: 2
INNER JOIN: 0
LEFT JOIN: 0
RIGHT JOIN: 0
CROSS JOIN: 0
SELF JOIN: 0
LEFT OUTER JOIN: 0
RIGHT OUTER JOIN: 0
OUTER JOIN: 0
UNION: 0
UNION ALL: 0
EXCEPT: 0
EXCEPT ALL: 0
INTERSECT: 0
INTERSECT ALL: 0
ORDER BY: 1
GROUP BY: 0
WITH: 1
HAVING: 0
DISTINCT: 0
LIMIT: 1
OFFSET: 0
LIKE: 0
IN: 1
BETWEEN: 2
IS NULL: 0
IS NOT NULL: 0
NULL: 0
COUNT: 0
SUM: 0
AVG: 0
MAX: 0
MIN: 0
EXISTS: 0
ANY: 0
ALL: 0
COALESCE: 0
IFNULL: 0
RANK(): 0
DENSE_RANK(): 0
ROW_NUMBER(): 0

Total logical lines (including functions and keywords): 26

--- Operation Counts ---
Found 'JOIN': 2 occurrence(s)
Found 'ORDER BY': 1 occurrence(s)
Found 'WITH': 1 occurrence(s)
Found 'LIMIT': 1 occurrence(s)
Found 'IN': 1 occurrence(s)
Found 'BETWEEN': 2 occurrence(s)

Total logical lines (functions/keywords in uppercase): 26
Total operations count: 8
Complexity score (operations per logical line): 0.31
SQL Query after removing comments and excess whitespace:
WITH banking_companies_ratios AS (
SELECT
fr.stock_code,
fr.year,
fr.quarter,
fr.ratio_code AS category_code,
fr.data
FROM
financial_ratio fr
WHERE
fr.stock_code IN ('BID', 'EIB', 'OCB', 'CTG', 'VCB', 'ACB', 'MBB', 'HDB', 'TPB', 'VPB', 'STB', 'TCB', 'SHB', 'VIB', 'ABB', 'LPB', 'NVB')
AND fr.ratio_code IN ('ROE', 'ROA')
AND fr.date_added BETWEEN '2020-01-01' AND '2024-09-30'
AND fr.quarter != 0
),
industry_averages AS (
SELECT
ifr.year,
ifr.quarter,
ifr.ratio_code AS category_code,
ifr.data_mean AS industry_average
FROM
industry_financial_ratio ifr
WHERE
ifr.industry = 'Banking'
AND ifr.ratio_code IN ('ROE', 'ROA')
AND ifr.date_added BETWEEN '2020-01-01' AND '2024-09-30'
AND ifr.quarter != 0
)
SELECT
bcr.stock_code,
bcr.quarter,
bcr.year,
bcr.category_code,
bcr.data AS company_ratio,
ia.industry_average
FROM
banking_companies_ratios bcr
JOIN
industry_averages ia
ON
bcr.year = ia.year
AND bcr.quarter = ia.quarter
AND bcr.category_code = ia.category_code
ORDER BY
bcr.stock_code,
bcr.year,
bcr.quarter,
bcr.category_code
LIMIT 100;

--- Breakdown of SQL Query Counting ---
JOIN: 1
INNER JOIN: 0
LEFT JOIN: 0
RIGHT JOIN: 0
CROSS JOIN: 0
SELF JOIN: 0
LEFT OUTER JOIN: 0
RIGHT OUTER JOIN: 0
OUTER JOIN: 0
UNION: 0
UNION ALL: 0
EXCEPT: 0
EXCEPT ALL: 0
INTERSECT: 0
INTERSECT ALL: 0
ORDER BY: 1
GROUP BY: 0
WITH: 1
HAVING: 0
DISTINCT: 0
LIMIT: 1
OFFSET: 0
LIKE: 0
IN: 3
BETWEEN: 2
IS NULL: 0
IS NOT NULL: 0
NULL: 0
COUNT: 0
SUM: 0
AVG: 0
MAX: 0
MIN: 0
EXISTS: 0
ANY: 0
ALL: 0
COALESCE: 0
IFNULL: 0
RANK(): 0
DENSE_RANK(): 0
ROW_NUMBER(): 0

Total logical lines (including functions and keywords): 27

--- Operation Counts ---
Found 'JOIN': 1 occurrence(s)
Found 'ORDER BY': 1 occurrence(s)
Found 'WITH': 1 occurrence(s)
Found 'LIMIT': 1 occurrence(s)
Found 'IN': 3 occurrence(s)
Found 'BETWEEN': 2 occurrence(s)

Total logical lines (functions/keywords in uppercase): 27
Total operations count: 9
Complexity score (operations per logical line): 0.33
SQL Query after removing comments and excess whitespace:
WITH food_and_beverage_companies AS (
SELECT
stock_code
FROM
company_info
WHERE
industry = 'Food and Beverages'
),
company_gpm AS (
SELECT
fr.stock_code,
fr.year,
fr.quarter,
fr.data AS company_gpm,
fr.date_added
FROM
financial_ratio fr
JOIN
food_and_beverage_companies fbc ON fr.stock_code = fbc.stock_code
WHERE
fr.ratio_code = 'GPM'
AND fr.date_added BETWEEN '2020-01-01' AND '2024-09-30'
AND fr.quarter != 0
),
industry_gpm AS (
SELECT
ifr.year,
ifr.quarter,
ifr.data_mean AS industry_gpm,
ifr.date_added
FROM
industry_financial_ratio ifr
WHERE
ifr.industry = 'Food and Beverages'
AND ifr.ratio_code = 'GPM'
AND ifr.date_added BETWEEN '2020-01-01' AND '2024-09-30'
AND ifr.quarter != 0
)
SELECT
cg.stock_code,
cg.quarter,
cg.year,
cg.company_gpm,
ig.industry_gpm,
(cg.company_gpm - ig.industry_gpm) AS gpm_difference,
cg.date_added
FROM
company_gpm cg
JOIN
industry_gpm ig ON cg.year = ig.year AND cg.quarter = ig.quarter
ORDER BY
cg.stock_code, cg.year, cg.quarter
LIMIT 100;

--- Breakdown of SQL Query Counting ---
JOIN: 2
INNER JOIN: 0
LEFT JOIN: 0
RIGHT JOIN: 0
CROSS JOIN: 0
SELF JOIN: 0
LEFT OUTER JOIN: 0
RIGHT OUTER JOIN: 0
OUTER JOIN: 0
UNION: 0
UNION ALL: 0
EXCEPT: 0
EXCEPT ALL: 0
INTERSECT: 0
INTERSECT ALL: 0
ORDER BY: 1
GROUP BY: 0
WITH: 1
HAVING: 0
DISTINCT: 0
LIMIT: 1
OFFSET: 0
LIKE: 0
IN: 0
BETWEEN: 2
IS NULL: 0
IS NOT NULL: 0
NULL: 0
COUNT: 0
SUM: 0
AVG: 0
MAX: 0
MIN: 0
EXISTS: 0
ANY: 0
ALL: 0
COALESCE: 0
IFNULL: 0
RANK(): 0
DENSE_RANK(): 0
ROW_NUMBER(): 0

Total logical lines (including functions and keywords): 26

--- Operation Counts ---
Found 'JOIN': 2 occurrence(s)
Found 'ORDER BY': 1 occurrence(s)
Found 'WITH': 1 occurrence(s)
Found 'LIMIT': 1 occurrence(s)
Found 'BETWEEN': 2 occurrence(s)

Total logical lines (functions/keywords in uppercase): 26
Total operations count: 7
Complexity score (operations per logical line): 0.27
SQL Query after removing comments and excess whitespace:
WITH company_tie AS (
SELECT
fr.stock_code,
fr.year,
fr.quarter,
fr.ratio_code,
fr.data AS company_tie_ratio
FROM
financial_ratio fr
JOIN
company_info ci ON fr.stock_code = ci.stock_code
WHERE
fr.ratio_code = 'TIE'
AND ci.industry = 'Chemicals'
AND fr.stock_code IN ('CSV', 'GVR', 'DGC', 'DCM', 'LAS', 'PLC')
AND fr.year BETWEEN 2020 AND 2023
AND fr.quarter = 0
),
industry_avg_tie AS (
SELECT
ifr.year,
ifr.quarter,
ifr.ratio_code,
ifr.data_mean AS industry_avg_tie_ratio
FROM
industry_financial_ratio ifr
WHERE
ifr.ratio_code = 'TIE'
AND ifr.industry = 'Chemicals'
AND ifr.year BETWEEN 2020 AND 2023
AND ifr.quarter = 0
)
SELECT
ct.stock_code,
ct.year,
ct.quarter,
ct.ratio_code,
ct.company_tie_ratio,
ia.industry_avg_tie_ratio
FROM
company_tie ct
JOIN
industry_avg_tie ia ON ct.year = ia.year AND ct.quarter = ia.quarter
ORDER BY
ct.stock_code, ct.year;

--- Breakdown of SQL Query Counting ---
JOIN: 2
INNER JOIN: 0
LEFT JOIN: 0
RIGHT JOIN: 0
CROSS JOIN: 0
SELF JOIN: 0
LEFT OUTER JOIN: 0
RIGHT OUTER JOIN: 0
OUTER JOIN: 0
UNION: 0
UNION ALL: 0
EXCEPT: 0
EXCEPT ALL: 0
INTERSECT: 0
INTERSECT ALL: 0
ORDER BY: 1
GROUP BY: 0
WITH: 1
HAVING: 0
DISTINCT: 0
LIMIT: 0
OFFSET: 0
LIKE: 0
IN: 1
BETWEEN: 2
IS NULL: 0
IS NOT NULL: 0
NULL: 0
COUNT: 0
SUM: 0
AVG: 0
MAX: 0
MIN: 0
EXISTS: 0
ANY: 0
ALL: 0
COALESCE: 0
IFNULL: 0
RANK(): 0
DENSE_RANK(): 0
ROW_NUMBER(): 0

Total logical lines (including functions and keywords): 25

--- Operation Counts ---
Found 'JOIN': 2 occurrence(s)
Found 'ORDER BY': 1 occurrence(s)
Found 'WITH': 1 occurrence(s)
Found 'IN': 1 occurrence(s)
Found 'BETWEEN': 2 occurrence(s)

Total logical lines (functions/keywords in uppercase): 25
Total operations count: 7
Complexity score (operations per logical line): 0.28
SQL Query after removing comments and excess whitespace:
WITH food_beverage_companies AS (
SELECT
stock_code
FROM
company_info
WHERE
industry = 'Food and Beverages'
AND exchange = 'HOSE'
),
inventory_turnover_data AS (
SELECT
fr.stock_code,
fr.year,
fr.quarter,
fr.data AS inventory_turnover
FROM
financial_ratio fr
JOIN
food_beverage_companies fbc ON fr.stock_code = fbc.stock_code
WHERE
fr.ratio_code = 'TAT' -- Assuming 'TAT' is the ratio code for Inventory Turnover
AND fr.date_added BETWEEN '2021-01-01' AND '2024-09-30'
AND fr.quarter != 0
),
inventory_turnover_trend AS (
SELECT
stock_code,
year,
quarter,
inventory_turnover,
LAG(inventory_turnover) OVER (PARTITION BY stock_code ORDER BY year, quarter) AS prev_inventory_turnover
FROM
inventory_turnover_data
)
SELECT
stock_code,
year,
quarter,
inventory_turnover,
CASE
WHEN prev_inventory_turnover IS NULL THEN NULL
ELSE (inventory_turnover - prev_inventory_turnover) / prev_inventory_turnover * 100
END AS percentage_change
FROM
inventory_turnover_trend
ORDER BY
stock_code, year, quarter
LIMIT 100;

--- Breakdown of SQL Query Counting ---
JOIN: 1
INNER JOIN: 0
LEFT JOIN: 0
RIGHT JOIN: 0
CROSS JOIN: 0
SELF JOIN: 0
LEFT OUTER JOIN: 0
RIGHT OUTER JOIN: 0
OUTER JOIN: 0
UNION: 0
UNION ALL: 0
EXCEPT: 0
EXCEPT ALL: 0
INTERSECT: 0
INTERSECT ALL: 0
ORDER BY: 2
GROUP BY: 0
WITH: 1
HAVING: 0
DISTINCT: 0
LIMIT: 1
OFFSET: 0
LIKE: 0
IN: 0
BETWEEN: 1
IS NULL: 1
IS NOT NULL: 0
NULL: 2
COUNT: 0
SUM: 0
AVG: 0
MAX: 0
MIN: 0
EXISTS: 0
ANY: 0
ALL: 0
COALESCE: 0
IFNULL: 0
RANK(): 0
DENSE_RANK(): 0
ROW_NUMBER(): 0

Total logical lines (including functions and keywords): 22

--- Operation Counts ---
Found 'JOIN': 1 occurrence(s)
Found 'ORDER BY': 2 occurrence(s)
Found 'WITH': 1 occurrence(s)
Found 'LIMIT': 1 occurrence(s)
Found 'BETWEEN': 1 occurrence(s)
Found 'IS NULL': 1 occurrence(s)
Found 'NULL': 2 occurrence(s)

Total logical lines (functions/keywords in uppercase): 22
Total operations count: 9
Complexity score (operations per logical line): 0.41
SQL Query after removing comments and excess whitespace:
SELECT
fr.stock_code,
fr.year,
fr.quarter,
'NPM' AS category_code,
fr.data AS net_profit_margin
FROM
financial_ratio fr
WHERE
fr.ratio_code = 'NPM'
AND fr.stock_code IN ('MWG', 'FRT', 'PSD')
AND fr.date_added BETWEEN '2020-01-01' AND '2024-09-30'
AND fr.quarter != 0
ORDER BY
fr.stock_code, fr.year, fr.quarter;
SELECT
ifr.industry,
ifr.year,
ifr.quarter,
'NPM' AS category_code,
ifr.data_mean AS industry_average_net_profit_margin
FROM
industry_financial_ratio ifr
WHERE
ifr.ratio_code = 'NPM'
AND ifr.industry = 'Retail'
AND ifr.date_added BETWEEN '2020-01-01' AND '2024-09-30'
AND ifr.quarter != 0
ORDER BY
ifr.year, ifr.quarter;
SELECT
fs.stock_code,
fs.year,
fs.quarter,
fs.category_code,
fs.data
FROM
financial_statement fs
WHERE
fs.stock_code IN ('MWG', 'FRT', 'PSD')
AND fs.date_added BETWEEN '2020-01-01' AND '2024-09-30'
AND fs.quarter != 0
AND fs.category_code IN ('IS_001', 'IS_002', 'IS_020', 'IS_060', 'IS_100') -- Revenue, Deductions, Net Revenue, Operating Profit, Net Income
ORDER BY
fs.stock_code, fs.year, fs.quarter;

--- Breakdown of SQL Query Counting ---
JOIN: 0
INNER JOIN: 0
LEFT JOIN: 0
RIGHT JOIN: 0
CROSS JOIN: 0
SELF JOIN: 0
LEFT OUTER JOIN: 0
RIGHT OUTER JOIN: 0
OUTER JOIN: 0
UNION: 0
UNION ALL: 0
EXCEPT: 0
EXCEPT ALL: 0
INTERSECT: 0
INTERSECT ALL: 0
ORDER BY: 3
GROUP BY: 0
WITH: 0
HAVING: 0
DISTINCT: 0
LIMIT: 0
OFFSET: 0
LIKE: 0
IN: 3
BETWEEN: 3
IS NULL: 0
IS NOT NULL: 0
NULL: 0
COUNT: 0
SUM: 0
AVG: 0
MAX: 0
MIN: 0
EXISTS: 0
ANY: 0
ALL: 0
COALESCE: 0
IFNULL: 0
RANK(): 0
DENSE_RANK(): 0
ROW_NUMBER(): 0

Total logical lines (including functions and keywords): 30

--- Operation Counts ---
Found 'ORDER BY': 3 occurrence(s)
Found 'IN': 3 occurrence(s)
Found 'BETWEEN': 3 occurrence(s)

Total logical lines (functions/keywords in uppercase): 30
Total operations count: 9
Complexity score (operations per logical line): 0.30
SQL Query after removing comments and excess whitespace:
SELECT
fr.stock_code,
fr.quarter,
fr.year,
fr.ratio_code,
fr.data
FROM
financial_ratio fr
JOIN
company_info ci
ON
fr.stock_code = ci.stock_code
WHERE
ci.exchange = 'HOSE'
AND ci.stock_indices = 'VN30'
AND fr.ratio_code IN ('ROE', 'DTER')
AND fr.date_added BETWEEN '2020-01-01' AND '2024-09-30'
AND fr.quarter != 0
ORDER BY
fr.stock_code, fr.year, fr.quarter, fr.ratio_code
LIMIT 100;

--- Breakdown of SQL Query Counting ---
JOIN: 1
INNER JOIN: 0
LEFT JOIN: 0
RIGHT JOIN: 0
CROSS JOIN: 0
SELF JOIN: 0
LEFT OUTER JOIN: 0
RIGHT OUTER JOIN: 0
OUTER JOIN: 0
UNION: 0
UNION ALL: 0
EXCEPT: 0
EXCEPT ALL: 0
INTERSECT: 0
INTERSECT ALL: 0
ORDER BY: 1
GROUP BY: 0
WITH: 0
HAVING: 0
DISTINCT: 0
LIMIT: 1
OFFSET: 0
LIKE: 0
IN: 1
BETWEEN: 1
IS NULL: 0
IS NOT NULL: 0
NULL: 0
COUNT: 0
SUM: 0
AVG: 0
MAX: 0
MIN: 0
EXISTS: 0
ANY: 0
ALL: 0
COALESCE: 0
IFNULL: 0
RANK(): 0
DENSE_RANK(): 0
ROW_NUMBER(): 0

Total logical lines (including functions and keywords): 13

--- Operation Counts ---
Found 'JOIN': 1 occurrence(s)
Found 'ORDER BY': 1 occurrence(s)
Found 'LIMIT': 1 occurrence(s)
Found 'IN': 1 occurrence(s)
Found 'BETWEEN': 1 occurrence(s)

Total logical lines (functions/keywords in uppercase): 13
Total operations count: 5
Complexity score (operations per logical line): 0.38
SQL Query after removing comments and excess whitespace:
SELECT
fr.stock_code,
fr.quarter,
fr.year,
fr.ratio_code AS category_code,
fr.data
FROM
financial_ratio fr
JOIN
map_category_code_ratio mccr
ON
fr.ratio_code = mccr.ratio_code
WHERE
fr.stock_code IN ('VNM', 'MSN')
AND fr.ratio_code IN ('DTAR', 'TIE')
AND fr.date_added BETWEEN '2020-01-01' AND '2024-09-30'
AND fr.quarter != 0
ORDER BY
fr.stock_code, fr.year, fr.quarter;

--- Breakdown of SQL Query Counting ---
JOIN: 1
INNER JOIN: 0
LEFT JOIN: 0
RIGHT JOIN: 0
CROSS JOIN: 0
SELF JOIN: 0
LEFT OUTER JOIN: 0
RIGHT OUTER JOIN: 0
OUTER JOIN: 0
UNION: 0
UNION ALL: 0
EXCEPT: 0
EXCEPT ALL: 0
INTERSECT: 0
INTERSECT ALL: 0
ORDER BY: 1
GROUP BY: 0
WITH: 0
HAVING: 0
DISTINCT: 0
LIMIT: 0
OFFSET: 0
LIKE: 0
IN: 2
BETWEEN: 1
IS NULL: 0
IS NOT NULL: 0
NULL: 0
COUNT: 0
SUM: 0
AVG: 0
MAX: 0
MIN: 0
EXISTS: 0
ANY: 0
ALL: 0
COALESCE: 0
IFNULL: 0
RANK(): 0
DENSE_RANK(): 0
ROW_NUMBER(): 0

Total logical lines (including functions and keywords): 12

--- Operation Counts ---
Found 'JOIN': 1 occurrence(s)
Found 'ORDER BY': 1 occurrence(s)
Found 'IN': 2 occurrence(s)
Found 'BETWEEN': 1 occurrence(s)

Total logical lines (functions/keywords in uppercase): 12
Total operations count: 5
Complexity score (operations per logical line): 0.42
SQL Query after removing comments and excess whitespace:
SELECT
fr.stock_code,
fr.quarter,
fr.year,
fr.ratio_code,
fr.data AS company_gpm,
ifr.data_mean AS industry_avg_gpm
FROM financial_ratio fr
JOIN industry_financial_ratio ifr
ON fr.ratio_code = ifr.ratio_code
AND fr.year = ifr.year
AND fr.quarter = ifr.quarter
AND ifr.industry = 'Real Estate'
WHERE fr.ratio_code = 'GPM'
AND fr.stock_code IN ('VHM', 'NVL') -- Vinhomes and Novaland
AND fr.date_added BETWEEN '2020-01-01' AND '2024-09-30'
AND fr.quarter != 0 -- Exclude annual reports
ORDER BY fr.stock_code, fr.year, fr.quarter
LIMIT 100;

--- Breakdown of SQL Query Counting ---
JOIN: 1
INNER JOIN: 0
LEFT JOIN: 0
RIGHT JOIN: 0
CROSS JOIN: 0
SELF JOIN: 0
LEFT OUTER JOIN: 0
RIGHT OUTER JOIN: 0
OUTER JOIN: 0
UNION: 0
UNION ALL: 0
EXCEPT: 0
EXCEPT ALL: 0
INTERSECT: 0
INTERSECT ALL: 0
ORDER BY: 1
GROUP BY: 0
WITH: 0
HAVING: 0
DISTINCT: 0
LIMIT: 1
OFFSET: 0
LIKE: 0
IN: 1
BETWEEN: 1
IS NULL: 0
IS NOT NULL: 0
NULL: 0
COUNT: 0
SUM: 0
AVG: 0
MAX: 0
MIN: 0
EXISTS: 0
ANY: 0
ALL: 0
COALESCE: 0
IFNULL: 0
RANK(): 0
DENSE_RANK(): 0
ROW_NUMBER(): 0

Total logical lines (including functions and keywords): 15

--- Operation Counts ---
Found 'JOIN': 1 occurrence(s)
Found 'ORDER BY': 1 occurrence(s)
Found 'LIMIT': 1 occurrence(s)
Found 'IN': 1 occurrence(s)
Found 'BETWEEN': 1 occurrence(s)

Total logical lines (functions/keywords in uppercase): 15
Total operations count: 5
Complexity score (operations per logical line): 0.33
SQL Query after removing comments and excess whitespace:
SELECT
fs1.stock_code,
fs1.year,
fs1.quarter,
'CF_050/IS_001' AS category_code,  -- Custom category code for the calculated ratio
(fs1.data / fs2.data) AS data      -- Operating Cash Flow to Sales Ratio
FROM
financial_statement fs1
JOIN
financial_statement fs2
ON
fs1.stock_code = fs2.stock_code
AND fs1.year = fs2.year
AND fs1.quarter = fs2.quarter
WHERE
fs1.stock_code = 'FPT'
AND fs1.category_code = 'CF_050'  -- Net cash flow from operating activities
AND fs2.category_code = 'IS_001'  -- Revenue from sales and services rendered
AND fs1.date_added BETWEEN '2020-01-01' AND '2024-09-30'
AND fs1.quarter != 0  -- Ensure we are looking at quarterly data
ORDER BY
fs1.year, fs1.quarter;

--- Breakdown of SQL Query Counting ---
JOIN: 1
INNER JOIN: 0
LEFT JOIN: 0
RIGHT JOIN: 0
CROSS JOIN: 0
SELF JOIN: 0
LEFT OUTER JOIN: 0
RIGHT OUTER JOIN: 0
OUTER JOIN: 0
UNION: 0
UNION ALL: 0
EXCEPT: 0
EXCEPT ALL: 0
INTERSECT: 0
INTERSECT ALL: 0
ORDER BY: 1
GROUP BY: 0
WITH: 0

In [17]:
sql_complexity_df

,id,question,sql_query,complexity_result
0,242d4217-33d1-4c53-9922-17a6d0a4b8d2,Analyze the trend of the Return on Assets (ROA...,-- ### quarterly_roa_trend_vcb_acb_2020_to_q3_...,"{'total_lines': 10, 'operations': {'JOIN': 0, ..."
1,e9def022-01c5-4dce-a223-103ae6913cd9,Analyze the price-to-earnings (P/E) ratio for...,-- ### P/E Ratio Analysis for Retail Companies...,"{'total_lines': 25, 'operations': {'JOIN': 2, ..."
2,c9ae9e06-2903-43c8-97ff-4398bdba15be,What were the interest coverage ratios for the...,-- ### interest_coverage_ratio_utilities_compa...,"{'total_lines': 26, 'operations': {'JOIN': 2, ..."
3,52f49b81-e91d-4ff3-82cf-a2a62ca14800,"For the banking companies (BID, EIB, OCB, CTG,...",-- ### banking_companies_roe_roa_2020_to_q3_20...,"{'total_lines': 27, 'operations': {'JOIN': 1, ..."
4,04da7098-1b47-45cc-b2c5-d288de57e5c3,Analyze the Gross Profit Margin for each compa...,-- ### food_and_beverage_companies_gpm_vs_indu...,"{'total_lines': 26, 'operations': {'JOIN': 2, ..."
...,...,...,...,...
540,762f5ce2-ff19-47ae-8cd5-b5d8e3c0542c,What was the average Return on Equity (ROE) fo...,-- ### Average ROE for companies listed on HOS...,"{'total_lines': 11, 'operations': {'JOIN': 1, ..."
541,5df0ddd9-7239-4fd3-bf46-2b21e92060cd,Compare the change in the average current rati...,-- ### average_current_and_quick_ratio_hose_20...,"{'total_lines': 28, 'operations': {'JOIN': 3, ..."
542,76427903-715b-4774-ae8b-d892d831fcf1,For the banking sector companies listed on the...,-- ### Banking Sector Companies in VN30: Net P...,"{'total_lines': 17, 'operations': {'JOIN': 0, ..."
543,b7a67beb-eecd-45cb-8edf-d2908dcfc33c,Compare the trend of total assets and total li...,-- ### banking_sector_total_assets_liabilities...,"{'total_lines': 28, 'operations': {'JOIN': 3, ..."
544,29f816d7-fa57-421f-97e9-09a81d1b2e4e,What were the average revenue growth rates and...,-- ### Average Revenue Growth Rates and Net Pr...,"{'total_lines': 20, 'operations': {'JOIN': 1, ..."